apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s5n1ivbel-python
  janus-idp.io/tekton: s5n1ivbel-python
  backstage.io/kubernetes-id: s5n1ivbel-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s5n1ivbel-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
